services:
  - type: web
    name: Keosu-Melbet-blog
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        value: your-secret-key-here
